### ISSUE TITLE
[Compatibility] Make it node v10 compatible

### ISSUE THREAD

**Issue by Louies89** [DopplerHQ/gitops-secrets-nodejs#24]
@ryan-blunden 

**Problem**:
The `exports` field in `package.json` is compateble with node v12 and above, so to make it compatible with lower versions I made the below changes and tested it in my project where I use node v10.

**Solution**:
Create `index.js` & `no-fs.js` file in same lavel where `package.json` is present and put below code in those files as shown below:

```js
// index.js
module.exports = require('./src');

```

```js
// index.js
module.exports = require('./src/no-fs');

```

And I have tested the functionality, it works fine.

Please make the changes as soon as possible, waiting to use the library in our projects.

Thank You

**Comment by Piccirello** [comment]
Thanks for the suggestion. Node 10 is no longer supported and thus this repo does not support it either. I recommend upgrading to Node 14.

**Comment by Louies89** [comment]
@Piccirello 
Can we add those 2 files at least so that at least the imports will work?
