### ISSUE TITLE
Module Not Found Issue

### ISSUE THREAD

**Issue by Louies89** [DopplerHQ/gitops-secrets-nodejs#25]
```js
const secrets = require("gitops-secrets/no-fs");
```
Above code is creating Module not found error.

In the attached image it can be seen, the `getServerSideProps()` (part of NextJs) is trying to call `loadSecrets()` which is a auto generated file by `gitops-secrets`, but the module is not getting imported correctly & the bellow error occurs

```
Module not found: Can't resolve 'gitops-secrets/no-fs'
```
Environment used : NextJs (10.0.5), Node v12.22.12

![image](https://user-images.githubusercontent.com/30086899/169715782-4b417190-a152-411b-9d69-4a08e850029f.png)

@ryan-blunden @Piccirello Please help...

**Comment by ryan-blunden** [comment]
Hi @Louies89. Sorry, but we won't be adding support for Node.js 10 as it reached its official end of life on April 30th 2021.

I've added a comment to your pull request #26 showing how to install the module from your fork, which will solve the issue.
